#!/bin/sh

# Switch to repo toplevel directory
pushd $(git rev-parse --show-toplevel)/.git/hooks

echo "Symlinking git-hooks/pre-commit into .git/hooks"
ln -s -f ../../git-hooks/pre-commit pre-commit

popd
