version: '3.7'
services:
  # app:
  #     build: .
  #     environment:
  #       PORT: "${PORT}"
  #     ports:
  #       - ${PORT}:${PORT}
  #     volumes:
  #       - ./src:/app/src
  #       - ./package.json:/app/package.json
  #       - ./package-lock.json:/app/package-lock.json

  db:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
        MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
