version: '3.7'
services:
  app-frontend:
    image: threesgame.azurecr.io/threes-frontend
    restart: always
    depends_on:
      - app-backend
    ports:
      - 80:80
      - 443:443

  app-backend:
    image: threesgame.azurecr.io/threes-backend
    restart: always
    env_file:
      - backend.env
    environment:
      PORT: 80
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_NAME}'
    volumes:
      - /var/lib/mongodb/data:/data/db
