version: '3.7'
services:
  app-frontend:
    image: threes-frontend
    restart: always
    env_file:
      - frontend.env
    depends_on:
      - app-backend
    profiles:
      - app

  app-backend:
    image: threes-backend
    restart: always
    env_file:
      - backend.env
    environment:
      PORT: 80
    depends_on:
      - db
    profiles:
      - app

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_NAME}'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
    driver: azure_file
    driver_opts:
      share_name: threes_mongo_data
      storage_account_name: threesgamestorage
