# This is only used for building and pushing the images

version: '3.7'

services:
  frontend-bundle:
    image: threesgame.azurecr.io/threes-frontend-bundle
    build:
      context: ../frontend
      args:
        REACT_APP_NAME: ${REACT_APP_NAME:-Threes Scorekeeper}
        REACT_APP_CLARITY_KEY: ${REACT_APP_CLARITY_KEY:-}
        REACT_APP_GOOGLE_ANALYTICS_KEY: ${REACT_APP_GOOGLE_ANALYTICS_KEY:-}

  backend:
    image: threesgame.azurecr.io/threes-backend
    build:
      context: ../backend
