version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - backend
      - frontend-bundle
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend-www:/var/www:ro

  frontend-bundle:
    extends:
      file: docker-compose.build.yml
      service: frontend-bundle
    restart: 'no'
    volumes:
      - ./frontend-www:/var/www

  backend:
    extends:
      file: docker-compose.build.yml
      service: backend
    restart: always
    env_file:
      - backend.env
    environment:
      PORT: 80
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_NAME}'
    volumes:
      - /var/lib/mongodb/data:/data/db
