# This is only used for building and pushing the images

version: '3.7'

services:
  frontend-bundle:
    image: threesgame.azurecr.io/threes-frontend-bundle
    build:
      context: ../frontend

  backend:
    image: threesgame.azurecr.io/threes-backend
    build:
      context: ../backend
