version: '3.7'

services:
  app-front-proxy:
    extends:
      file: docker-compose.build.yml
      service: app-front-proxy
    restart: always
    depends_on:
      - app-backend
      - app-frontend-bundle
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend-www:/var/www

  app-frontend-bundle:
    extends:
      file: docker-compose.build.yml
      service: app-frontend-bundle
    restart: never
    volumes:
      - ./frontend-www:/var/www

  app-backend:
    extends:
      file: docker-compose.build.yml
      service: app-frontend-bundle
    restart: always
    env_file:
      - backend.env
    environment:
      PORT: 80
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_NAME}'
    volumes:
      - /var/lib/mongodb/data:/data/db
