# This is only used for building and pushing the images

services:
  frontend-bundle:
    image: nathan815/threes-frontend-bundle
    build:
      context: ../frontend
      args:
        REACT_APP_NAME: ${REACT_APP_NAME:-Threes Scorekeeper}
        REACT_APP_CLARITY_KEY: ${REACT_APP_CLARITY_KEY:-}
        REACT_APP_GOOGLE_ANALYTICS_KEY: ${REACT_APP_GOOGLE_ANALYTICS_KEY:-}

  backend:
    image: nathan815/threes-backend
    build:
      context: ../backend
