---
- hosts: all
  become: true
  gather_facts: false
  environment:
    AZ_SP_ID: "{{ AZ_SP_ID }}"
    AZ_SP_PW: "{{ AZ_SP_PW }}"
    AZ_SP_TENANT: "{{ AZ_SP_TENANT }}"
    AZ_VAULT: "{{ AZ_VAULT }}"

  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Upload files to /app
      copy:
        src: "{{ item.src | default(item) }}"
        dest: "{{ item.dest | default('/app') }}"
      loop:
        - ../backend.template.env
        - ../docker-compose.build.yml
        - ../docker-compose.yml
        - ../nginx

    - name: Generate env files
      script: ./generate_env.sh
      args:
        chdir: /app

    - name: Login to Azure using az cli
      shell: az login --service-principal -u $AZ_SP_ID -p $AZ_SP_PW --tenant $AZ_SP_TENANT

    - name: Docker Login ACR
      shell: az acr login --name threesgame

    - name: Pull latest container images
      shell: docker-compose pull
      args:
        chdir: /app

    - name: Restart containers
      shell: docker-compose up -d --remove-orphans
      args:
        chdir: /app

    - name: Reload test-nginx config
      include_role:
        name: reload-nginx
      vars:
        nginx_service_name: test-nginx

    - name: Validate test-nginx (local) is reachable
      uri:
        url: http://localhost:9980
        follow_redirects: none
        status_code: [301]

    - name: Reload real nginx config
      include_role:
        name: reload-nginx
      vars:
        nginx_service_name: nginx

    - name: Validate website is reachable (HTTP)
      uri:
        url: http://{{ domain }}

    - name: Validate website is reachable (HTTPS)
      uri:
        url: https://{{ domain }}
