- hosts: all
  become: true
  environment:
    AZ_SP_ID: "{{ AZ_SP_ID }}"
    AZ_SP_PW: "{{ AZ_SP_PW }}"
    AZ_SP_TENANT: "{{ AZ_SP_TENANT }}"
    AZ_VAULT: "{{ AZ_VAULT }}"

  roles:
    - app-server

  tasks:
    - name: Upload files to /app
      copy:
        src: "{{ item.src | default(item) }}"
        dest: "{{ item.dest | default('/app') }}"
      loop:
        - ../backend.template.env
        - ../docker-compose.build.yml
        - ../docker-compose.yml

    - name: Generate env files
      script: ./generate_env.sh
      args:
        chdir: /app

    - name: Login to Azure using az cli
      shell: az login --service-principal -u $AZ_SP_ID -p $AZ_SP_PW --tenant $AZ_SP_TENANT

    - name: Docker Login ACR
      shell: az acr login --name threesgame

    - name: Pull latest container images
      shell: env $(cat backend.env) docker-compose pull
      args:
        chdir: /app

    - name: Restart containers
      shell: env $(cat backend.env) docker-compose up -d
      args:
        chdir: /app
