#!/bin/sh

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

START_DIR=$(pwd)

# Switch to repo toplevel directory
cd $(git rev-parse --show-toplevel)

echo "Checking ./frontend"
pushd frontend
npx lint-staged
popd

echo "Checking ./backend"
pushd backend
npx lint-staged
popd

# Go back to directory when we started
cd "$START_DIR"
