---
- name: Ensure /app directory exists
  file:
    path: /app
    state: directory

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Azure CLI
  include_role:
    name: darkwizard242.azurecli

- include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker

- include_role:
    name: geerlingguy.docker
  vars:
    docker_users:
      - app
