---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker

- include_role:
    name: geerlingguy.docker
  vars:
    docker_users:
      - app
