name: Backend CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
    paths:
      - backend/**
      - .github/workflows/backend.yml
  pull_request:
    branches: [ main ]
    paths:
      - backend/**
      - .github/workflows/backend.yml

jobs:
  build:
    defaults:
      run:
        working-directory: backend

    runs-on: ubuntu-latest
    environment: build

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        working-directory: infra
        run: |
          docker compose -f docker-compose.build.yml build backend
          IMAGE_SHA=${{ github.sha }}
          docker tag nathan815/threes-backend nathan815/threes-backend:${IMAGE_SHA:0:7}
          docker tag nathan815/threes-backend nathan815/threes-backend:latest

      - name: Push backend image to Docker Hub
        working-directory: infra
        run: |
          docker compose -f docker-compose.build.yml push backend
          docker push nathan815/threes-backend:${{ github.sha }}
          docker push nathan815/threes-backend:latest
