name: Renew SSL certificate

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 15 * *'

jobs:
  renew_ssl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run playbook on server to renew SSL certificate
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: certbot_renew.yml
          directory: ./infra/ansible
          key: ${{ secrets.APP_SERVER_SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ vars.APP_SERVER_HOSTNAME }} ansible_connection=ssh ansible_user=app_server_user
          requirements: galaxy-requirements.yml
