---
name: Prod Deploy

on:
  push:
    branches: [main]

jobs:
  wait-for-tests:
    name: Wait for CI
    runs-on: ubuntu-latest

    steps:
      - name: Wait for all other workflows
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: Wait for CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  docker-build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    environment: production

    needs: [wait-for-tests]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: '${{ secrets.ACR_SERVER }}'
          username: '${{ secrets.ACR_USERNAME }}'
          password: '${{ secrets.ACR_PASSWORD }}'

      - name: Enable caching of Docker image layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build Docker images
        working-directory: infra
        run: |
          docker-compose -f docker-compose.build.yml build

      - name: Push Docker images to ACR
        working-directory: infra
        run: |
          docker-compose -f docker-compose.build.yml push

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    needs: [docker-build]

    steps:
      - uses: actions/checkout@v2

      - name: Run Deploy Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./infra/ansible
          key: ${{ secrets.APP_SERVER_SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ vars.APP_SERVER_HOSTNAME }} ansible_connection=ssh ansible_user=app_server_user
          requirements: galaxy-requirements.yml
          options: |
            -e AZ_SP_ID=${{ secrets.AZ_SP_ID }}
            -e AZ_SP_PW=${{ secrets.AZ_SP_PW }}
            -e AZ_SP_TENANT=${{ secrets.AZ_SP_TENANT }}
            -e AZ_VAULT=${{ secrets.AZ_VAULT }}
            --verbose
